In [1]:
import pandas as pd

df = pd.read_csv("Web_Scrapped_websites.csv", encoding="latin1")
df

,Country_Rank,Website,Trustworthiness,Avg_Daily_Visitors,Child_Safety,Avg_Daily_Pageviews,Privacy,Facebook_likes,Twitter_mentions,Google_pluses,...,Month_Average_Daily_Reach_percentage,Daily_Pageviews_percentage,Month_Average_Daily_Pageviews_percentage,Daily_Pageviews_per_user_percentage,Location,Hosted_by,Subnetworks,Registrant,Registrar,country
0,1,www.google.com.af,Excellent,NaN,Excellent,NaN,Excellent,9,1,37,...,1.0,-5.1,12.5,-4.1,United States,Google Inc.,216.58.203.227,NaN,NaN,Afghanistan
1,2,www.google.com,Excellent,515 007 350,Excellent,4 192 159 833,Excellent,94.2K,11.2K,11.7M,...,-1.1,1.8,-6.3,2.1,United States,Google Inc.,216.58.194.100,DNS Admin (Google Inc.),MARKMONITOR INC.,Afghanistan
2,3,www.youtube.com,Excellent,506 457 282,Excellent,2 679 159 025,Excellent,13.5K,16.5K,19.3M,...,1.8,9.7,0.5,3.8,United States,Google Inc.,172.217.2.238,DNS Admin (Google Inc.),MARKMONITOR INC.,Afghanistan
3,4,www.facebook.com,Excellent,270 071 255,Good,1 082 985 733,Excellent,5.87M,64.4K,127K,...,-1.5,-8.2,-2.2,-8.2,Ireland,Facebook,31.13.73.36,"Domain Administrator (Facebook, Inc.)",MARKMONITOR INC.,Afghanistan
4,5,www.yahoo.com,Excellent,99 572 035,Excellent,383 352 336,Excellent,17.2K,1.11K,798K,...,-0.8,-4.9,-0.5,-3.2,United States,Yahoo! Inc.,"98.139.180.149, 98.139.183.24",Domain Administrator (Yahoo! Inc.),MARKMONITOR INC.,Afghanistan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9535,46,www.newsdzezimbabwe.co.uk,Unknown,11 862,Unknown,51 010,Unknown,-,15,3,...,5.7,9.6,23.9,28.6,United States,Google Inc.,172.217.9.179,Name withheld. This Registrant is using a priv...,Nominet UK,Zimbabwe
9536,47,www.nehandaradio.com,Unknown,9 946,Unknown,19 894,Unknown,3,256,214,...,-19.3,66.8,-41.1,86.0,United States,"CloudFlare, Inc.","104.25.125.117, 104.25.126.117","Registration Private (Domains By Proxy, LLC)","GODADDY.COM, LLC",Zimbabwe
9537,48,www.mysagagame.com,Very poor,3 076 664,Very poor,4 091 963,Very poor,-,-,-,...,70.4,-12.4,70.1,-0.7,United States,"Webzilla, Inc.",NaN,"WHOIS AGENT (WHOIS PRIVACY PROTECTION SERVICE,...","ENOM, INC.",Zimbabwe
9538,49,www.ntd.tv,Unsatisfactory,163 932,Good,216 392,Unsatisfactory,1,-,158,...,32.6,1.0,19.2,-17.0,United States,"CloudFlare, Inc.","104.20.224.31, 104.20.225.31",Taiqi Ran (NTD),"NAME.COM, INC.",Zimbabwe
9539,50,www.emailaccessonline.com,Poor,1 331 630,Unknown,1 717 804,Poor,-,-,4,...,3.8,-4.3,5.7,-0.7,United States,Amazon Technologies Inc.,"34.202.76.242, 52.4.230.116",Domain Admin (Whois Privacy Corp.),INTERNET DOMAIN SERVICE BS CORP,Zimbabwe

In [2]:
df.isnull().sum()     # checking null values

Country_Rank                                   0
Website                                        0
Trustworthiness                                0
Avg_Daily_Visitors                           144
Child_Safety                                   0
Avg_Daily_Pageviews                          144
Privacy                                        0
Facebook_likes                                 0
Twitter_mentions                               0
Google_pluses                                  0
LinkedIn_mentions                              0
Pinterest_pins                                 0
StumbleUpon_views                              0
Status                                         0
Traffic_Rank                                   1
Reach_Day                                     62
Month_Average_Daily_Reach                     45
Daily_Pageviews                               62
Month_Average_Daily_Pageviews                 46
Daily_Pageviews_per_user                      62
Reach_Day_percentage                          77
Month_Average_Daily_Reach_percentage          82
Daily_Pageviews_percentage                    77
Month_Average_Daily_Pageviews_percentage      81
Daily_Pageviews_per_user_percentage          437
Location                                      73
Hosted_by                                    124
Subnetworks                                  270
Registrant                                  1000
Registrar                                    961
country                                        0
dtype: int64

In [3]:
df = df.drop(columns=["Registrant", "Registrar","Daily_Pageviews_per_user_percentage","Subnetworks"])  #removing more null values and unecessary columns

In [4]:
df["Facebook_likes"] = df["Facebook_likes"].str.replace("-","0")          #replacing values
df["fln"] = df["Facebook_likes"].replace(r"[A-Za-z]","",regex=True)       #replacing only letters with ""
df["flc"] = df["Facebook_likes"].replace(r"[^A-Za-z]","",regex=True)      #replacing only numbers with ""
df["flc1"] = df["flc"].map({"K":1000, "M":100000})                         #replacing values using map
df = df.drop(columns=["flc"])                                             #removing this col because we assigned values in above step
df["fln"] = df["fln"].astype(float)                                       #converting to float datatype
df["facebook_likes"] = df["fln"] * df["flc1"]
df = df.drop(columns=["fln","flc1","Facebook_likes"])
# df

In [5]:
# df.isnull().sum()

df = df.dropna()                            #removing the rows nan values are less than 10%
df = df.reset_index()                       #reseting the index for order
df = df.drop(columns=["index"])             #remove level_0, sometimes it will come
# df.isna().sum()
df["Avg_Daily_Visitors"] = df["Avg_Daily_Visitors"].str.replace(" ","").astype(int)         #removing spaces and converting datatype
df["Avg_Daily_Pageviews"] = df["Avg_Daily_Pageviews"].str.replace(" ","").astype(int)       #removing spaces and converting datatype
df

,Country_Rank,Website,Trustworthiness,Avg_Daily_Visitors,Child_Safety,Avg_Daily_Pageviews,Privacy,Twitter_mentions,Google_pluses,LinkedIn_mentions,...,Month_Average_Daily_Pageviews,Daily_Pageviews_per_user,Reach_Day_percentage,Month_Average_Daily_Reach_percentage,Daily_Pageviews_percentage,Month_Average_Daily_Pageviews_percentage,Location,Hosted_by,country,facebook_likes
0,2,www.google.com,Excellent,515007350,Excellent,4192159833,Excellent,11.2K,11.7M,1.67K,...,7.564032,6.5760,-0.3,-1.1,1.8,-6.3,United States,Google Inc.,Afghanistan,94200.0
1,3,www.youtube.com,Excellent,506457282,Excellent,2679159025,Excellent,16.5K,19.3M,60K,...,5.045568,5.2416,5.5,1.8,9.7,0.5,United States,Google Inc.,Afghanistan,13500.0
2,4,www.facebook.com,Excellent,270071255,Good,1082985733,Excellent,64.4K,127K,6.23K,...,2.016960,3.5904,0.0,-1.5,-8.2,-2.2,Ireland,Facebook,Afghanistan,587000.0
3,5,www.yahoo.com,Excellent,99572035,Excellent,383352336,Excellent,1.11K,798K,7.5K,...,0.703910,3.5808,-1.8,-0.8,-4.9,-0.5,United States,Yahoo! Inc.,Afghanistan,17200.0
4,14,www.msn.com,Excellent,22403678,Excellent,71019660,Excellent,679,98.5K,247,...,0.131040,3.0144,-11.4,1.1,-12.9,1.2,United States,Microsoft Corporation,Afghanistan,47200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1582,5,www.facebook.com,Excellent,270071255,Good,1082985733,Excellent,64.4K,127K,6.23K,...,2.016960,3.5904,0.0,-1.5,-8.2,-2.2,Ireland,Facebook,Zimbabwe,587000.0
1583,6,www.yahoo.com,Excellent,99572035,Excellent,383352336,Excellent,1.11K,798K,7.5K,...,0.703910,3.5808,-1.8,-0.8,-4.9,-0.5,United States,Yahoo! Inc.,Zimbabwe,17200.0
1584,23,www.msn.com,Excellent,22403678,Excellent,71019660,Excellent,679,98.5K,247,...,0.131040,3.0144,-11.4,1.1,-12.9,1.2,United States,Microsoft Corporation,Zimbabwe,47200.0
1585,34,www.thepiratebay.org,Excellent,8339803,Good,47703675,Excellent,23K,625,1.19K,...,0.086189,5.6064,27.8,5.0,44.0,7.3,United States,"CloudFlare, Inc.",Zimbabwe,1430.0
1586,43,www.whatsapp.com,Excellent,21528030,Excellent,25618356,Excellent,118,637K,6.71K,...,0.047290,1.1712,-2.1,0.4,-2.5,0.4,United States,WhatsApp Inc.,Zimbabwe,166000.0

In [6]:
# !pip install autotg
# import autotg as atg
# atg.find_best_target(df)

In [7]:
y = df["Avg_Daily_Visitors"]                                                                                #choosing target
X = df[["Avg_Daily_Pageviews","Website","Trustworthiness","Child_Safety","Privacy","Location","facebook_likes"]]             #selecting features for the target
# X.nunique()
# X.dtypes

In [8]:
#importing modules
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_extraction.text import TfidfVectorizer

#seperating for transformers
num_cols = ["Avg_Daily_Pageviews","facebook_likes"]
cat_cols = ["Trustworthiness","Child_Safety", "Privacy"]
text_col1 = 'Website'
text_col2 = 'Location'

preprocessor = ColumnTransformer(
  transformers=[
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(), cat_cols),
    ("txt1", TfidfVectorizer(), text_col1),
    ("txt2", TfidfVectorizer(), text_col2)
  ]
)

model = Pipeline(
  steps=[
    ("prepocessing", preprocessor),
    ("regression", RandomForestRegressor())
  ]
)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)         #training and testing

model.fit(X_train, y_train)               #fitting the model on training data

Pipeline(steps=[('prepocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Avg_Daily_Pageviews',
                                                   'facebook_likes']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Trustworthiness',
                                                   'Child_Safety', 'Privacy']),
                                                 ('txt1', TfidfVectorizer(),
                                                  'Website'),
                                                 ('txt2', TfidfVectorizer(),
                                                  'Location')])),
                ('regression', RandomForestRegressor())])

In [9]:
y_pred = model.predict(X_test)            #predicting the test data
y_pred

array([2.70071255e+08, 5.06457282e+08, 9.95720350e+07, 2.70071255e+08,
       5.15007350e+08, 2.70071255e+08, 5.18108189e+08, 5.06457282e+08,
       5.06457282e+08, 2.24036780e+07, 9.95720350e+07, 2.70071255e+08,
       1.76788920e+07, 5.18108189e+08, 8.33980300e+06, 5.06457282e+08,
       1.76788920e+07, 1.76788920e+07, 2.24036780e+07, 2.49335511e+07,
       5.06457282e+08, 2.70071255e+08, 9.95720350e+07, 9.95720350e+07,
       3.19787913e+08, 8.33980300e+06, 9.95720350e+07, 1.85140580e+07,
       2.70071255e+08, 7.34044200e+06, 2.70071255e+08, 4.88204140e+07,
       5.06457282e+08, 2.70071255e+08, 5.06457282e+08, 2.70071255e+08,
       5.06457282e+08, 2.24036780e+07, 2.70071255e+08, 8.33980300e+06,
       9.58227337e+06, 8.33980300e+06, 1.82822700e+07, 4.88204140e+07,
       2.24036780e+07, 1.19635918e+07, 2.24036780e+07, 4.88204140e+07,
       4.84289700e+06, 1.65392210e+07, 5.18108189e+08, 2.15280300e+07,
       5.15007350e+08, 1.76788920e+07, 5.06457282e+08, 2.70071255e+08,
       2.51711300e+07, 2.70071255e+08, 5.15007350e+08, 2.24036780e+07,
       9.95720350e+07, 5.06457282e+08, 1.76788920e+07, 2.70071255e+08,
       2.70071255e+08, 1.85140580e+07, 5.18108189e+08, 2.70071255e+08,
       5.06457282e+08, 2.70071255e+08, 1.65449536e+08, 2.15280300e+07,
       1.76788920e+07, 2.70071255e+08, 5.06457282e+08, 9.95720350e+07,
       1.76788920e+07, 2.95450256e+08, 5.15007350e+08, 3.26867762e+08,
       1.76788920e+07, 2.15280300e+07, 2.70071255e+08, 9.95720350e+07,
       1.76788920e+07, 5.06457282e+08, 2.24036780e+07, 9.95720350e+07,
       5.06457282e+08, 1.65392210e+07, 9.95720350e+07, 4.48277200e+04,
       9.95720350e+07, 1.65392210e+07, 1.76788920e+07, 5.06457282e+08,
       2.24036780e+07, 5.15007350e+08, 5.18108189e+08, 2.24036780e+07,
       1.76788920e+07, 2.24036780e+07, 5.18108189e+08, 2.70071255e+08,
       9.95720350e+07, 4.88204140e+07, 2.89379549e+06, 5.06457282e+08,
       2.24036780e+07, 2.70071255e+08, 5.06457282e+08, 2.51711300e+07,
       9.95720350e+07, 1.76788920e+07, 2.61057010e+07, 2.70071255e+08,
       9.95720350e+07, 5.18108189e+08, 1.86448220e+07, 1.93196366e+06,
       1.76788920e+07, 5.18108189e+08, 5.06457282e+08, 2.93330784e+07,
       1.82822700e+07, 2.15280300e+07, 1.65392210e+07, 7.34044200e+06,
       9.95720350e+07, 2.15280300e+07, 8.33980300e+06, 5.15007350e+08,
       8.35096219e+06, 8.33980300e+06, 1.50725400e+06, 1.76788920e+07,
       5.06457282e+08, 9.95720350e+07, 1.65392210e+07, 2.24036780e+07,
       5.18108189e+08, 1.65392210e+07, 1.76788920e+07, 2.15280300e+07,
       2.70071255e+08, 5.06457282e+08, 2.15280300e+07, 4.84289700e+06,
       4.88204140e+07, 2.70071255e+08, 5.18108189e+08, 9.95720350e+07,
       2.70071255e+08, 2.24036780e+07, 1.76788920e+07, 5.06457282e+08,
       4.88204140e+07, 5.06457282e+08, 5.18108189e+08, 1.34627342e+06,
       1.76788920e+07, 8.33980300e+06, 1.65392210e+07, 2.24036780e+07,
       9.95720350e+07, 8.33980300e+06, 4.88204140e+07, 5.06457282e+08,
       4.88204140e+07, 5.15007350e+08, 2.15280300e+07, 3.61010387e+08,
       5.18108189e+08, 5.18108189e+08, 5.18108189e+08, 1.82822700e+07,
       5.06457282e+08, 2.70071255e+08, 5.94601080e+05, 5.06457282e+08,
       5.18108189e+08, 8.33980300e+06, 2.24036780e+07, 1.65392210e+07,
       5.18108189e+08, 4.88204140e+07, 5.06457282e+08, 2.24036780e+07,
       5.18108189e+08, 2.24036780e+07, 4.88204140e+07, 2.51711300e+07,
       9.95720350e+07, 2.70071255e+08, 8.68452050e+05, 2.15280300e+07,
       3.19793947e+08, 5.18108189e+08, 5.06457282e+08, 1.75209099e+08,
       2.69869574e+07, 8.33980300e+06, 2.24036780e+07, 3.61016421e+08,
       9.95720350e+07, 3.19787913e+08, 2.24036780e+07, 2.70071255e+08,
       2.24036780e+07, 1.86448220e+07, 2.24036780e+07, 2.70071255e+08,
       2.09813815e+06, 5.06457282e+08, 1.50725400e+06, 1.76788920e+07,
       5.06457282e+08, 5.06457282e+08, 2.24036780e+07, 4.88204140e+07,
       3.90744781e+06, 4.88204140e+07, 2.15280300e+07, 2.24036780e+07,
       5.06457282e+08, 2.70071255e+08, 5.18108189e+08, 2.51711300e+07,
       2.51711300e+07, 2.70071255e+08, 5.06457282e+08, 9.95720350e+07,
       2.70071255e+08, 2.15280300e+07, 2.01408433e+08, 2.24036780e+07,
       1.75071437e+08, 6.04333960e+05, 2.70071255e+08, 4.88204140e+07,
       9.95720350e+07, 5.15007350e+08, 9.95720350e+07, 2.15280300e+07,
       5.18108189e+08, 1.30189580e+06, 6.55824815e+07, 1.76788920e+07,
       1.50725400e+06, 9.95720350e+07, 9.95720350e+07, 5.18108189e+08,
       1.82822700e+07, 1.76788920e+07, 4.88204140e+07, 5.15007350e+08,
       9.95720350e+07, 2.15280300e+07, 5.15007350e+08, 5.18108189e+08,
       5.06457282e+08, 5.06457282e+08, 9.95720350e+07, 1.50725400e+06,
       5.06457282e+08, 5.18108189e+08, 4.84289700e+06, 1.76788920e+07,
       6.55824815e+07, 4.84289700e+06, 8.33980300e+06, 5.18108189e+08,
       4.88204140e+07, 1.43808004e+07, 5.18108189e+08, 2.51711300e+07,
       2.70071255e+08, 2.70071255e+08, 2.70071255e+08, 3.88610696e+06,
       9.95720350e+07, 5.15007350e+08, 4.88204140e+07, 2.15280300e+07,
       2.70071255e+08, 2.24036780e+07, 2.70071255e+08, 1.65392210e+07,
       2.61057010e+07, 5.06457282e+08, 2.70071255e+08, 1.82822700e+07,
       5.06457282e+08, 8.33980300e+06, 5.18108189e+08, 2.15280300e+07,
       4.88204140e+07, 5.18108189e+08, 2.24036780e+07, 5.06457282e+08,
       9.95720350e+07, 8.33980300e+06, 2.61057010e+07, 9.95720350e+07,
       9.95720350e+07, 1.65449201e+08, 8.33980300e+06, 4.08185539e+06,
       9.95720350e+07, 9.95720350e+07, 5.18108189e+08, 2.61057010e+07,
       4.88204140e+07, 2.24036780e+07, 2.70071255e+08, 2.51711300e+07,
       5.06457282e+08, 1.82822700e+07])

In [10]:
# model.score(X_train, y_train)               #training score checiking
model.score(X_test, y_test)                 #testing score checking
                                            #here we got overfitting for that we are adding more inputs

0.9323473373939075

In [11]:
import joblib
joblib.dump(model, "Final.py")

['Final.py']